language: ruby
env:
  matrix:
  - DISPLAY=:99.0
  global:
  - MANSHAR_HOME=/home/travis/build/manshar/manshar
  - SECRET_TOKEN=a59d98c49d5a9b6ccf7e14cc35cb005e1ba9ab6656070e4c05e5df95d07afd44f98fd48552a68ac83e6dc3440691db011ef635c0c1a74102964686e7d51f3bf3
  - DRAGONFLY_SECRET=c2jq0a9cj039jc01mamc09qjc930ur10fjafj0a9fj09fj23qnweocn0qwf0qfjq
  - secure: Ek/EsKA4yC6RrhlHNhlSsztud+UxFxbvwiaEkqIo2MTo1ewr40/7k8JLuONgYNHL47/ZKvzqXfRiD+Zq18xIXNEO8KyIf3ASLmhMYOLQsPZIsmCSUgnBpwpfiO9tiuAf4ww5+A8sD4Ob4xnkLpwB961bBn1RyIKN6mymuxzdtPw=
rvm:
  - 2.3.0
before_install:
  - cd /usr/lib/git-core/
  - sudo wget https://raw.github.com/apenwarr/git-subtree/master/git-subtree.sh
  - sudo mv git-subtree.sh git-subtree
  - sudo chmod 755 git-subtree
  - cd $MANSHAR_HOME/backend
  - sudo apt-get update -qq
  - curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo apt-get install redis-server
before_script:
  - cd $MANSHAR_HOME/backend
  - cp config/database.yml.sample config/database.yml
  - psql -c 'create database manshar_test;' -U postgres
  - bundle exec rake db:migrate
  - cd $MANSHAR_HOME/web-client
  - npm install -g npm@latest
  - npm install -g gulp
  - npm install
  - sh -e /etc/init.d/xvfb start
  - bower install
  - sudo redis-server /etc/redis/redis.conf
bundler_args: --without development
script:
  - cd $MANSHAR_HOME/web-client && gulp build:production && cd $MANSHAR_HOME/backend && bundle exec rspec
matrix:
  allow_failures:
  - rvm: ruby-head
after_success:
  - cd $MANSHAR_HOME
  - ./utils/travis/deploy.sh
notifications:
  slack: manshar:CPhqeSFN8hlY3duA8vlMzDeB

